package com.example.domain;

import java.util.Date;

public class Articles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer favorite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_id
     *
     * @return the value of articles.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_id
     *
     * @param articleId the value for articles.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.name
     *
     * @return the value of articles.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.name
     *
     * @param name the value for articles.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.content
     *
     * @return the value of articles.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.content
     *
     * @param content the value for articles.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.favorite
     *
     * @return the value of articles.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getFavorite() {
        return favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.favorite
     *
     * @param favorite the value for articles.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.creator
     *
     * @return the value of articles.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.creator
     *
     * @param creator the value for articles.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.created_at
     *
     * @return the value of articles.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.created_at
     *
     * @param createdAt the value for articles.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.updater
     *
     * @return the value of articles.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.updater
     *
     * @param updater the value for articles.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.updated_at
     *
     * @return the value of articles.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.updated_at
     *
     * @param updatedAt the value for articles.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.version
     *
     * @return the value of articles.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.version
     *
     * @param version the value for articles.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}