package com.example.domain;

import java.util.Date;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer favorite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_id
     *
     * @return the value of comments.comment_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_id
     *
     * @param commentId the value for comments.comment_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.name
     *
     * @return the value of comments.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.name
     *
     * @param name the value for comments.name
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.favorite
     *
     * @return the value of comments.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getFavorite() {
        return favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.favorite
     *
     * @param favorite the value for comments.favorite
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param articleId the value for comments.article_id
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.creator
     *
     * @return the value of comments.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.creator
     *
     * @param creator the value for comments.creator
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.created_at
     *
     * @return the value of comments.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.created_at
     *
     * @param createdAt the value for comments.created_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.updater
     *
     * @return the value of comments.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.updater
     *
     * @param updater the value for comments.updater
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.updated_at
     *
     * @return the value of comments.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.updated_at
     *
     * @param updatedAt the value for comments.updated_at
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.version
     *
     * @return the value of comments.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.version
     *
     * @param version the value for comments.version
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}