package com.example.mapper;

import com.example.domain.Articles;
import com.example.domain.ArticlesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int countByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int deleteByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    List<Articles> selectByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    Articles selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int updateByExampleSelective(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int updateByExample(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Sat May 23 11:39:08 JST 2020
     */
    int updateByPrimaryKey(Articles record);
}